### ISSUE TITLE
Request props for scale the height & width or radius

### ISSUE THREAD

**Issue by mutiadianita** [stssoftware/react-native-svg-circular-progress#3]
I want to make it smaller? is there any solution for me to scale it?

**Comment by klaudialax** [comment]
I had the same issue - couldn't make it smaller. 
I've edited the code of the component and added _size_ parameter. I've made pull request, but it has not been accepted yet #2 .

**Comment by rudyhuynh** [comment]
Sorry for late response. I have much work lately. 
I just accepted @klaudialax merge request but not publish it yet because the `example` is quite out of date so I cannot run it now. Will upgrade and publish it to npm soon.

**Comment by rudyhuynh** [comment]
all are published
