### ISSUE TITLE
can we make it to have a stripped view 

### ISSUE THREAD

**Issue by koolkarni** [stssoftware/react-native-svg-circular-progress#4]
![screen shot 2018-06-18 at 5 54 45 pm](https://user-images.githubusercontent.com/16875126/41569804-5ca3915e-7321-11e8-8a95-37015facc7de.png)

**Comment by rudyhuynh** [comment]
My idea is to add a circle with white dashed stroke, sth like this:
```
<circle cx="50" cy="50" r="40" stroke="white" stroke-width="20" fill="transparent" stroke-dasharray="2 12" />
```
But I don't have time now. Feel free to create a PR or just fork my repo.
